<div class="page-header">
  <h1><span class="tweak-width">Homepage</span><small>Site simples em PHP</small></h1>
</div>
<div class="image">
	<img src="./library/images/computers.jpg"/>
</div>
<div class="content">
	<span class="title">Lorem ipsum dolor sit amet</span>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce dictum commodo leo, sit amet scelerisque nisi sodales ac. Suspendisse tristique egestas vehicula. Aliquam nec velit luctus est laoreet convallis eleifend nec elit. Maecenas non leo sed dui interdum laoreet a ultricies risus. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent at urna non mi egestas vestibulum faucibus ac ante. Nunc hendrerit justo a justo facilisis, vel posuere erat volutpat. Pellentesque facilisis eget lorem a egestas.</p>
	<p>Sed sit amet aliquet nibh, ac laoreet erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent bibendum cursus erat, ac vestibulum nulla aliquam eu. Curabitur eget diam ultrices, tincidunt massa eget, laoreet dolor. Mauris sed interdum metus. Mauris dapibus arcu lectus, in commodo felis blandit quis. Proin at luctus mauris. Pellentesque semper sem ligula, ut dignissim est congue a. Curabitur at posuere dui. Sed quis venenatis lorem. Nam lobortis diam ut tellus aliquet faucibus. Cras justo ante, fringilla sit amet orci in, sollicitudin tempor ligula. Integer malesuada, lectus sit amet convallis bibendum, odio purus mollis tellus, vestibulum lacinia est nulla nec leo. Nunc faucibus in sem auctor vehicula. Proin elementum elit non pharetra cursus.</p>
	<p>Cras risus magna, accumsan a dignissim vitae, condimentum nec lectus. Maecenas tempus vulputate convallis. Quisque facilisis ultrices imperdiet. Duis congue augue id libero sagittis, a ultrices massa fringilla. Nam sed lorem purus. Praesent non tellus non magna accumsan dictum a ut urna. Curabitur imperdiet, est a malesuada malesuada, dui eros mollis nisl, id pretium felis dolor id sapien. Proin ac varius erat. Nullam malesuada, dui quis condimentum venenatis, nisi orci vulputate erat, ac gravida metus nunc at nunc. Quisque leo leo, gravida eu nibh a, vehicula convallis diam. Mauris vitae maximus nisi, in maximus elit. Proin id rutrum mi, at vehicula justo. Aenean ullamcorper eget dolor quis vulputate.</p>	
</div>